// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/images/full.svg"
    | "/images/icon.svg"
    | "/images/icon128.png"
    | "/images/icon16.png"
    | "/images/icon48.png"
    | "/popup.html"
    | "/variables.css"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
